bezier:		bezier.cpp
		g++ -w -o bezier bezier.cpp -lm -framework OpenGL -framework GLUT -Wno-deprecated-declarations -Wno-c++11-compat-deprecated-writable-strings

catmull:		catmull.cpp
		g++ -w -o catmull catmull.cpp -lm -framework OpenGL -framework GLUT -Wno-deprecated-declarations -Wno-c++11-compat-deprecated-writable-strings
